gos_web_socket:
    server:
        port: '%env(WS_PORT)%'
        host: '%env(WS_HOST)%'
        router:
            resources:
                - '%kernel.project_dir%/src/Resources/websocket_routing.yaml'
    shared_config: true
    client:
        firewall: secured_area
        session_handler: '@session.handler.pdo'
    rpc:
        - '@rpc_sample_service'