gos_web_socket:
    server:
        port: '%env(WS_PORT)%'
        host: '%env(WS_HOST)%'
#        router:
#            resources:
#                - '@AcmeBundle/Resources/config/pubsub/routing.yml'
    shared_config: true
    client:
        firewall: main
        session_handler: '@session.handler.pdo'