gos_web_socket:
    server:
        port: '%env(WS_PORT)%'
        host: '%env(WS_HOST)%'
#        router:
#            resources:
#                - '@routes.yaml'
    shared_config: true
    client:
        firewall: [main, secured_area]
        session_handler: '@session.handler.pdo'