app_logout:
  path: /logout

default:
  path: /
  controller: App\Controller\DefaultController::index
  methods:    GET

profile:
  path: /profile
  controller: App\Controller\ProfileController::index
  methods:    GET|POST

user_project_list:
  path: /profile/project
  controller: App\Controller\ProfileController::project
  methods:    GET

user_settings:
  path: /profile/settings
  controller: App\Controller\ProfileController::settings
  methods:    GET

counter_form:
  path: /profile/counter_form
  controller: App\Controller\ProfileController::counterBlockForm
  methods: GET|POST

admin:
  path: /admin
  controller: App\Controller\AdminController::index
  methods: GET|POST

admin_test:
  path: /admin_test
  controller: App\Admin\AdminController::index
  methods: GET